version: '3.1'

services:
  testing-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${TEST_DATABASE_USER}
      POSTGRES_PASSWORD: ${TEST_DATABASE_PASSWORD}
      POSTGRES_DB: ${TEST_DATABASE_NAME}
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d/

  production-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    container_name: postgresProd
    ports:
      - "5436:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
